language: python
python: 2.7
sudo: false  # use new infrastructure
env:
  - TOX_ENV=py27

install:
  - pip install -r requirements.txt
  - pip install -r dev_requirements.txt

script:
- coverage run --source ethereum setup.py test
#- tox -e $TOX_ENV

after_success:
- coveralls
